### ISSUE TITLE
Easy way to create new titles

### ISSUE THREAD

**Issue by cuozzm** [rpitv/rpits#110]
It would be nice to have an easy way to create titles. By this I mean a button or something where I can select a blank lower third (one line, two line, split, etc.), credit graphic, etc. While it's not the most difficult thing to go and add it, the names of all of the graphics are confusing without pictures and the need for on-the-spot graphics comes up frequently enough. Thanks.

**Comment by asquared** [comment]
There should be a "+" drop down in the titles UI that lets you add a new
title.

**Comment by cuozzm** [comment]
Yes, but there's no easy way of knowing what any of these are.

**Comment by vreelb** [comment]
The functionality to add titles easily was added in 2c7e1ed.

Lack of title previews is addressed in #68 so I'm closing this as a duplicate.
