### ISSUE TITLE
"Force Render" button should update all fields

### ISSUE THREAD

**Issue by asquared** [rpitv/rpits#91]
Perhaps this is a matter of opinion, but I think the "Force Render" button should first trigger an update on all fields. Having to remember to press the "Update" button (or failing to when trying to quickly make a title) causes me to make lots of on-air mistakes.

**Comment by hamilr2** [comment]
Sounds good to me -- we had previously discussed making the fields auto-save, however there was some concern about wanting to be able to reset and/or cancel.

I can't imagine anyone would change a field, change their mind, and then press Force Render. Perhaps a reset button is at hand as well!

**Comment by vreelb** [comment]
I suppose this is as good a venue as any to posit that it would be good if we had a dev box set up somewhere that was easier to access than on the RPI network. Not sure if we want to go in on getting a VPS together or just making a VM on a dong machine that's laying around somewhere. In any case it would make doing development remotely a lot easier for me (and @hamilr2 as well, if the windows/cocaine method ever gets tiresome).

Anyway, if we did I'd probably be pushing a lot more little things every now and then, including this.

**Comment by hamilr2** [comment]
I'm generally a proponent of cocaine.
